name: asuna_video_player_example
description: Demonstrates how to use the asuna_video_player plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_barrage: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  asuna_video_player:
    path: ../

flutter:
  uses-material-design: true
